--------------------------------------------------------
--  파일이 생성됨 - 월요일-8월-21-2023   
--------------------------------------------------------
DROP TABLE "CANDYTOON"."ASK_TBL" cascade constraints;
DROP TABLE "CANDYTOON"."FNQ_TBL" cascade constraints;
DROP TABLE "CANDYTOON"."MEMBER_TBL" cascade constraints;
DROP TABLE "CANDYTOON"."NOTICE_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table ASK_TBL
--------------------------------------------------------

  CREATE TABLE "CANDYTOON"."ASK_TBL" 
   (	"ASK_NO" NUMBER, 
	"ASK_CATEGORY" VARCHAR2(100 BYTE), 
	"ASK_SUBJECT" VARCHAR2(200 BYTE), 
	"ASK_CONTENT" VARCHAR2(1000 BYTE), 
	"ASK_WRITER" VARCHAR2(50 BYTE), 
	"ASK_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FNQ_TBL
--------------------------------------------------------

  CREATE TABLE "CANDYTOON"."FNQ_TBL" 
   (	"FNQ_NO" NUMBER, 
	"FNQ_CATEGORY" VARCHAR2(100 BYTE), 
	"FNQ_SUBJECT" VARCHAR2(200 BYTE), 
	"FNQ_CONTENT" VARCHAR2(1000 BYTE), 
	"FNQ_WRITER" VARCHAR2(50 BYTE), 
	"FNQ_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "CANDYTOON"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(40 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(100 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"REGI_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTICE_TBL
--------------------------------------------------------

  CREATE TABLE "CANDYTOON"."NOTICE_TBL" 
   (	"NOTICE_NO" NUMBER, 
	"NOTICE_SUBJECT" VARCHAR2(200 BYTE), 
	"NOTICE_CONTENT" VARCHAR2(1000 BYTE), 
	"NOTICE_WRITER" VARCHAR2(50 BYTE), 
	"NOTICE_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CANDYTOON.ASK_TBL
SET DEFINE OFF;
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (2,'이벤트','문의','D','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (3,'결제/환불','환불문의','환불문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (4,'기타','1번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (5,'기타','2번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (6,'기타','3번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (7,'기타','4번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (8,'기타','5번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (9,'기타','6번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (10,'기타','7번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (11,'기타','8번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (12,'기타','9번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (13,'기타','10번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (14,'기타','11번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (15,'기타','12번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (16,'기타','13번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (17,'기타','14번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (18,'기타','15번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (19,'기타','16번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (20,'기타','17번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (21,'기타','18번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (22,'기타','19번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (23,'기타','20번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (24,'사이트이용','21번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (25,'사이트이용','22번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (26,'사이트이용','23번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (27,'사이트이용','24번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (28,'사이트이용','25번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (29,'사이트이용','26번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (30,'사이트이용','27번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (31,'사이트이용','28번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (32,'사이트이용','29번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (33,'사이트이용','30번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (34,'사이트이용','31번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (35,'사이트이용','32번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (36,'사이트이용','33번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (37,'사이트이용','34번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (38,'사이트이용','35번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
REM INSERTING into CANDYTOON.FNQ_TBL
SET DEFINE OFF;
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (1,'기타','기타1번째 안내','기타1번째 내용','admin',to_timestamp('23/08/21 14:25:47.344000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (2,'기타','기타2번째 안내','기타2번째 내용','admin',to_timestamp('23/08/21 14:25:47.344000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (3,'기타','기타3번째 안내','기타3번째 내용','admin',to_timestamp('23/08/21 14:25:47.344000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (4,'결제/환불','결제/환불1번째 안내','결제/환불1번째 내용','admin',to_timestamp('23/08/21 14:26:16.947000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (5,'결제/환불','결제/환불2번째 안내','결제/환불2번째 내용','admin',to_timestamp('23/08/21 14:26:16.947000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (6,'결제/환불','결제/환불3번째 안내','결제/환불3번째 내용','admin',to_timestamp('23/08/21 14:26:16.947000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (7,'결제/환불','결제/환불4번째 안내','결제/환불4번째 내용','admin',to_timestamp('23/08/21 14:26:16.947000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (8,'결제/환불','결제/환불5번째 안내','결제/환불5번째 내용','admin',to_timestamp('23/08/21 14:26:16.947000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (9,'결제/환불','결제/환불6번째 안내','결제/환불6번째 내용','admin',to_timestamp('23/08/21 14:26:16.947000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (10,'회원/계정','회원/계정1번째 안내','회원/계정1번째 내용','admin',to_timestamp('23/08/21 14:26:32.645000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (11,'회원/계정','회원/계정2번째 안내','회원/계정2번째 내용','admin',to_timestamp('23/08/21 14:26:32.645000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (12,'회원/계정','회원/계정3번째 안내','회원/계정3번째 내용','admin',to_timestamp('23/08/21 14:26:32.645000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (13,'회원/계정','회원/계정4번째 안내','회원/계정4번째 내용','admin',to_timestamp('23/08/21 14:26:32.645000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (14,'회원/계정','회원/계정5번째 안내','회원/계정5번째 내용','admin',to_timestamp('23/08/21 14:26:32.645000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (15,'회원/계정','회원/계정6번째 안내','회원/계정6번째 내용','admin',to_timestamp('23/08/21 14:26:32.645000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (16,'사이트이용','사이트이용1번째 안내','사이트이용1번째 내용','admin',to_timestamp('23/08/21 14:26:49.625000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (17,'사이트이용','사이트이용2번째 안내','사이트이용2번째 내용','admin',to_timestamp('23/08/21 14:26:49.626000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (18,'사이트이용','사이트이용3번째 안내','사이트이용3번째 내용','admin',to_timestamp('23/08/21 14:26:49.626000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (19,'사이트이용','사이트이용4번째 안내','사이트이용4번째 내용','admin',to_timestamp('23/08/21 14:26:49.626000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (20,'사이트이용','사이트이용5번째 안내','사이트이용5번째 내용','admin',to_timestamp('23/08/21 14:26:49.626000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (21,'이벤트','이벤트1번째 안내','이벤트1번째 내용','admin',to_timestamp('23/08/21 14:27:01.384000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (22,'이벤트','이벤트2번째 안내','이벤트2번째 내용','admin',to_timestamp('23/08/21 14:27:01.385000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (23,'이벤트','이벤트3번째 안내','이벤트3번째 내용','admin',to_timestamp('23/08/21 14:27:01.385000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (24,'기타','기타1번째 안내','기타1번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (25,'기타','기타2번째 안내','기타2번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (26,'기타','기타3번째 안내','기타3번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (27,'기타','기타4번째 안내','기타4번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (29,'결제/환불','기타6번째 안내**','기타6번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (30,'기타','기타7번째 안내','기타7번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.FNQ_TBL (FNQ_NO,FNQ_CATEGORY,FNQ_SUBJECT,FNQ_CONTENT,FNQ_WRITER,FNQ_DATE) values (31,'기타','기타8번째 안내','기타8번째 내용','admin',to_timestamp('23/08/21 14:27:15.290000000','RR/MM/DD HH24:MI:SSXFF'));
REM INSERTING into CANDYTOON.MEMBER_TBL
SET DEFINE OFF;
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user01','pass01','user01@aaa.com','일일일',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user02','pass02','user02@bbb.com','이이이',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user03','pass03','user03@ccc.com','삼삼삼',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user04','pass04','user04@ddd.com','사사사',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user11','pass123','user11@naver.com','유저일',to_date('23/08/07','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user10','pass10','user10@naver.com','유저십',to_date('23/08/14','RR/MM/DD'));
REM INSERTING into CANDYTOON.NOTICE_TBL
SET DEFINE OFF;
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (1,'1번째 공지사항','공지내용1','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (2,'2번째 공지사항','공지내용2','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (3,'3번째 공지사항','공지내용3','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (4,'4번째 공지사항','공지내용4','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (5,'5번째 공지사항','공지내용5','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (6,'6번째 공지사항','공지내용6','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (7,'7번째 공지사항','공지내용7','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (8,'8번째 공지사항','공지내용8','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (9,'9번째 공지사항','공지내용9','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (10,'10번째 공지사항','공지내용10','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (11,'11번째 공지사항','공지내용11','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (12,'12번째 공지사항','공지내용12','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (13,'13번째 공지사항','공지내용13','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (14,'14번째 공지사항','공지내용14','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (15,'15번째 공지사항','공지내용15','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (16,'16번째 공지사항','공지내용16','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (17,'17번째 공지사항','공지내용17','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (18,'18번째 공지사항','공지내용18','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (19,'19번째 공지사항','공지내용19','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (20,'20번째 공지사항','공지내용20','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (21,'21번째 공지사항','공지내용21','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (22,'22번째 공지사항','공지내용22','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (23,'23번째 공지사항','공지내용23','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (37,'공지사항 추가','추가','admin',to_timestamp('23/08/21 01:29:02.954000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (25,'25번째 공지사항','공지내용25','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (26,'26번째 공지사항','공지내용26','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (27,'27번째 공지사항','공지내용27','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (28,'28번째 공지사항','공지내용28','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (30,'30번째 공지사항','공지내용30','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (31,'31번째 공지사항','공지내용31','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (32,'32번째 공지사항','공지내용32','admin',to_timestamp('23/08/20 17:42:22.224000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (33,'공지 추가 등록**','추가 등록','admin',to_timestamp('23/08/20 23:26:26.573000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (35,'공지 수정','test111','admin',to_timestamp('23/08/20 23:29:41.002000000','RR/MM/DD HH24:MI:SSXFF'));
Insert into CANDYTOON.NOTICE_TBL (NOTICE_NO,NOTICE_SUBJECT,NOTICE_CONTENT,NOTICE_WRITER,NOTICE_DATE) values (36,'Test 수정','test 수정','admin',to_timestamp('23/08/20 23:31:03.075000000','RR/MM/DD HH24:MI:SSXFF'));
--------------------------------------------------------
--  DDL for Index SYS_C007425
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANDYTOON"."SYS_C007425" ON "CANDYTOON"."ASK_TBL" ("ASK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007430
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANDYTOON"."SYS_C007430" ON "CANDYTOON"."FNQ_TBL" ("FNQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007332
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANDYTOON"."SYS_C007332" ON "CANDYTOON"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007040
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANDYTOON"."SYS_C007040" ON "CANDYTOON"."NOTICE_TBL" ("NOTICE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ASK_TBL
--------------------------------------------------------

  ALTER TABLE "CANDYTOON"."ASK_TBL" ADD PRIMARY KEY ("ASK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_WRITER" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FNQ_TBL
--------------------------------------------------------

  ALTER TABLE "CANDYTOON"."FNQ_TBL" ADD PRIMARY KEY ("FNQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDYTOON"."FNQ_TBL" MODIFY ("FNQ_WRITER" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."FNQ_TBL" MODIFY ("FNQ_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."FNQ_TBL" MODIFY ("FNQ_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."FNQ_TBL" MODIFY ("FNQ_CATEGORY" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "CANDYTOON"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDYTOON"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."MEMBER_TBL" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE_TBL
--------------------------------------------------------

  ALTER TABLE "CANDYTOON"."NOTICE_TBL" MODIFY ("NOTICE_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."NOTICE_TBL" MODIFY ("NOTICE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."NOTICE_TBL" MODIFY ("NOTICE_WRITER" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."NOTICE_TBL" ADD PRIMARY KEY ("NOTICE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
