--------------------------------------------------------
--  파일이 생성됨 - 화요일-8월-08-2023   
--------------------------------------------------------
DROP TABLE "CANDYTOON"."MEMBER_TBL" cascade constraints;
DROP TABLE "CANDYTOON"."ASK_TBL" cascade constraints;
--------------------------------------------------------
--  DDL for Table MEMBER_TBL
--------------------------------------------------------

  CREATE TABLE "CANDYTOON"."MEMBER_TBL" 
   (	"MEMBER_ID" VARCHAR2(20 BYTE), 
	"MEMBER_PW" VARCHAR2(40 BYTE), 
	"MEMBER_EMAIL" VARCHAR2(100 BYTE), 
	"MEMBER_NAME" VARCHAR2(50 BYTE), 
	"REGI_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ASK_TBL
--------------------------------------------------------

  CREATE TABLE "CANDYTOON"."ASK_TBL" 
   (	"ASK_NO" NUMBER, 
	"ASK_CATEGORY" VARCHAR2(100 BYTE), 
	"ASK_SUBJECT" VARCHAR2(200 BYTE), 
	"ASK_CONTENT" VARCHAR2(1000 BYTE), 
	"ASK_WRITER" VARCHAR2(50 BYTE), 
	"ASK_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CANDYTOON.MEMBER_TBL
SET DEFINE OFF;
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user01','pass777','user01@aaa.com','일일일',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user02','pass02','user02@bbb.com','이이이',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user03','pass03','user03@ccc.com','삼삼삼',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user04','pass04','user04@ddd.com','사사사',to_date('23/07/31','RR/MM/DD'));
Insert into CANDYTOON.MEMBER_TBL (MEMBER_ID,MEMBER_PW,MEMBER_EMAIL,MEMBER_NAME,REGI_DATE) values ('user11','pass123','user11@naver.com','유저일',to_date('23/08/07','RR/MM/DD'));
REM INSERTING into CANDYTOON.ASK_TBL
SET DEFINE OFF;
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (2,'이벤트','문의','D','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (3,'결제/환불','환불문의','환불문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (4,'기타','1번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (5,'기타','2번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (6,'기타','3번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (7,'기타','4번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (8,'기타','5번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (9,'기타','6번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (10,'기타','7번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (11,'기타','8번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (12,'기타','9번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (13,'기타','10번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (14,'기타','11번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (15,'기타','12번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (16,'기타','13번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (17,'기타','14번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (18,'기타','15번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (19,'기타','16번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (20,'기타','17번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (21,'기타','18번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (22,'기타','19번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (23,'기타','20번째 기타문의','기타문의','user03',to_date('23/08/03','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (24,'사이트이용','21번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (25,'사이트이용','22번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (26,'사이트이용','23번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (27,'사이트이용','24번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (28,'사이트이용','25번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (29,'사이트이용','26번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (30,'사이트이용','27번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (31,'사이트이용','28번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (32,'사이트이용','29번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (33,'사이트이용','30번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (34,'사이트이용','31번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (35,'사이트이용','32번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (36,'사이트이용','33번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (37,'사이트이용','34번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
Insert into CANDYTOON.ASK_TBL (ASK_NO,ASK_CATEGORY,ASK_SUBJECT,ASK_CONTENT,ASK_WRITER,ASK_DATE) values (38,'사이트이용','35번째 기타문의','기타문의','user03',to_date('23/08/04','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C007332
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANDYTOON"."SYS_C007332" ON "CANDYTOON"."MEMBER_TBL" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007348
--------------------------------------------------------

  CREATE UNIQUE INDEX "CANDYTOON"."SYS_C007348" ON "CANDYTOON"."ASK_TBL" ("ASK_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER_TBL
--------------------------------------------------------

  ALTER TABLE "CANDYTOON"."MEMBER_TBL" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDYTOON"."MEMBER_TBL" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."MEMBER_TBL" MODIFY ("MEMBER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."MEMBER_TBL" MODIFY ("MEMBER_PW" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ASK_TBL
--------------------------------------------------------

  ALTER TABLE "CANDYTOON"."ASK_TBL" ADD PRIMARY KEY ("ASK_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_WRITER" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "CANDYTOON"."ASK_TBL" MODIFY ("ASK_CATEGORY" NOT NULL ENABLE);
